# Generated by Django 4.1.7 on 2023-03-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="owner",
        ),
    ]
