# Generated by Django 4.1.7 on 2023-03-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_is_email_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_email_verified",
        ),
    ]
